mongo:
  image: mongo
houston:
  build: houston
  ports:
    - "3010:3000"
  links:
    - mongo:mongo
  environment:
    MONGO_URL: mongodb://mongo_1:27017/meteor
adminbase:
  build: .
  links:
    - mongo:mongo
  volumes:
    - ..:/adminbase
  ports:
    - "3000:3000"
  environment:
    MONGO_URL: mongodb://mongo_1:27017/meteor
